# -*- coding: utf-8 -*-
"""Projeto imigraçao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrpQ3kxlZYgmpskHLFT4vszduAyJDIKF
"""

import pandas as pd

df = pd.read_csv('/content/canadian_immegration_data_ptbr.csv')

#Importando dados do DataFrame

df

df.info()

#O ano como o Ídice.

df.set_index('País', inplace=True)

anos = list(map(str, range(1980, 2014)))

anos

brazil = df.loc['Brazil', anos]

brazil

brazil_dict = {'ano': brazil.index.tolist(), 'imigrantes': brazil.values.tolist()}
dados_brazil = pd.DataFrame(brazil_dict)

dados_brazil

#Importando o módulo pyplot com a biblioteca matplotlib e alterand os ticks dos eixos x e y
#Adicionar título ao gráfico e rótulos aos eixos x e y.

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.plot(dados_brazil['ano'], dados_brazil['imigrantes'])
plt.title('Imigranção do Brasil para o Canadá de 1980 a 2013')
plt.xlabel('Ano')
plt.ylabel('Número de imigrantes')
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.show()

#Exercício Imagração de Brasil e Argentina para o Canadá entre 1980 a 2013

df_comparacao = df.loc[['Brazil', 'Argentina'], anos]
df_comparacao

df_comparacao = df_comparacao.T
df_comparacao.head()

plt.plot(df_comparacao['Brazil'], label='Brasil')
plt.plot(df_comparacao['Argentina'], label='Argentina')
plt.title('Imigranção do Brasil e Argentina para o Canadá de 1980 a 2013')
plt.xlabel('Ano')
plt.ylabel('Número de imigrantes')
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.legend()
plt.show()

# Criando figura (customizando gráficos)

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(dados_brazil['ano'], dados_brazil['imigrantes'])
ax.set_title('Imigranção do Brasil para o Canadá \n1980 a 2013')
ax.set_xlabel('Ano')
ax.set_ylabel('Número de imigrantes')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))

plt.show()

#Criando subplots em uma direção

fig,axs = plt.subplots(1,2, figsize=(15,5))
axs[0].plot(dados_brazil['ano'], dados_brazil['imigrantes'])
axs[0].set_title ('Imigranção do Brasil para o Canadá \n1980 a 2013')
axs[0].set_xlabel('Ano')
axs[0].set_ylabel('Número de imigrantes')
axs[0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0].grid()


axs[1].boxplot(dados_brazil['imigrantes'])
axs[1].set_title ('Imigranção do Brasil para o Canadá \n1980 a 2013')
axs[1].set_xlabel('Ano')
axs[1].set_ylabel('Número de imigrantes')
axs[1].grid()

plt.show()

dados_brazil.describe()

#Criando subplots em 2 direçoes e ajustando todos os eixos para a mesma escala.
#Modificar espaçamento entre subplots
#Título geral para uma figura contendo subplots

fig, axs = plt.subplots(2,2, figsize=(10,6))
fig.subplots_adjust(hspace=0.5, wspace=0.3)
fig.suptitle('Imigração dos quatro maiores países para o Canadá de 1980 a 2013')

axs[0,0].plot(df.loc['Brazil', anos])
axs[0,0].set_title('Brasil')

axs[0,1].plot(df.loc['Colombia', anos])
axs[0,1].set_title('Colômbia')

axs[1,0].plot(df.loc['Argentina', anos])
axs[1,0].set_title('Argentina')

axs[1,1].plot(df.loc['Peru', anos])
axs[1,1].set_title('Peru')

for ax in axs.flat:
    ax.xaxis.set_major_locator(plt.MultipleLocator(5))

for ax in axs.flat:
    ax.set(xlabel='Ano', ylabel='Número de imigrantes')
    ax.grid()

ymin = 0
ymax = 7000

for ax in axs.ravel():
  ax.set_ylim(ymin, ymax)


plt.show()

#Personalizando visualizações com Matplotlib
#ticks e eixos, alternado o tamanhos da fontes, mudando posição do título e adicinonando marcadores(marker) e grades

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(dados_brazil['ano'], dados_brazil['imigrantes'], lw=3,)
ax.set_title('Imigranção do Brasil para o Canadá \n1980 a 2013', fontsize=18, loc='left')
ax.set_xlabel('Ano', fontsize=14)
ax.set_ylabel('Número de imigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

ax.xaxis.set_major_locator(plt.MultipleLocator(5))
plt.grid(linestyle='--')

plt.show()

print(plt.style.available)

#EstiloFiveThirtyEight

IPython_default = plt.rcParams.copy()

plt.rcParams.update(IPython_default);

#Alterando as cores

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(dados_brazil['ano'], dados_brazil['imigrantes'], lw=3, color='g')
ax.set_title('Imigranção do Brasil para o Canadá \n1980 a 2013', fontsize=18, loc='left')
ax.set_xlabel('Ano', fontsize=14)
ax.set_ylabel('Número de imigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

ax.xaxis.set_major_locator(plt.MultipleLocator(5))


plt.show()

df.head(10)

#Consulta os países da América do Sul

america_sul = df.query('Região == "South America"')

america_sul

america_sul_sorted = america_sul.sort_values('Total', ascending=True)
cores = ['royalblue', 'orange', 'forestgreen', 'orchid', 'purple', 'brown', 'slateblue','gray', 'olive','navy', 'teal', 'tomato']
fig, ax = plt.subplots(figsize=(12,5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'])
ax.set_title('Imagração da América do Sul para o Canadá \n1980 a 2013', loc='left',fontsize=18)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

plt.show()

#Ordenando o gráfico de barras do maior para o menor

america_sul_sorted = america_sul.sort_values('Total', ascending=True)

#Destacando o Brasil(país que esta sendo pesquisado).
#Adicionando valores a cada gráfico, realizando um for e retirando o eixo y
#Gráfico pronto

cores = []
for pais in america_sul_sorted.index:
    if pais == 'Brazil':
        cores.append('green')
    else:
        cores.append('silver')

fig, ax = plt.subplots(figsize=(12,5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'], color=cores)
ax.set_title('América do Sul: Brasil foi o quarto país com mais imigrantes \npara o Canadá no período de 1980 a 2013', loc='left',fontsize=18)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)


for i,v in enumerate(america_sul_sorted['Total']):
    ax.text(v+20, i, str(v), color='black', fontsize=10, ha='left', va='center')

ax.set_frame_on(False)
ax.get_xaxis().set_visible(False)
ax.tick_params(axis='both', which='both', length=0)

plt.show()

# Importando Bilioteca seaborn python
#Top 10 (dos 10 países com mair imigração)

import seaborn as sns

sns.set_theme()

top_10 = df.sort_values('Total', ascending=False).head(10)

top_10

#Plotando gráficos com a biblioteca seaborn

sns.barplot(data=top_10, x=top_10.index, y='Total')

sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h')

ax=sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h')
ax.set(title='Países com maior imigração para o Canadá\n1980 a 2013',
       xlabel='Número de imigrantes',
       ylabel='')

plt.show()

#Criando figura e personaliznado a visualização com a bilioteca Seaborn

fig, ax = plt.subplots (figsize=(8,4))
ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h')

ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=16)
ax.set_xlabel ('Número de imigrantes', fontsize=14)
ax.set_ylabel('')

plt.show()

def gerar_grafico_paleta(palette):
  fig, ax = plt.subplots(figsize=(8,4))
  ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette=palette)
  ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=18)
  ax.set_xlabel ('Número de imigrantes', fontsize=14)
  ax.set_ylabel('')

  plt.show()

gerar_grafico_paleta('Blues')

gerar_grafico_paleta('Blues_r')

gerar_grafico_paleta('rocket')

gerar_grafico_paleta('coolwarm')

gerar_grafico_paleta('tab10')

sns.set_theme(style='dark')
gerar_grafico_paleta('tab10')

sns.set_theme(style='whitegrid')
gerar_grafico_paleta('tab10')

sns.set_theme(style='white')
gerar_grafico_paleta('tab10')

sns.set_theme(style='ticks')
gerar_grafico_paleta('tab10')

fig, ax = plt.subplots(figsize=(8,4))
ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette='tab10')

ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=18)
ax.set_xlabel ('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
sns.despine()

plt.show()

#Criando e personalizando gráfico interativo com a biblioteca Plotly

import plotly.express as px

fig = px.line(dados_brazil, x='ano', y='imigrantes', title='Imigranção do Brasil para o Canadá no período 1980 a 2013')
fig.update_traces(line_color='green', line_width=4)

fig.update_layout(width=1000, height=500,
                  xaxis={'tickangle':-45},
                  font_family='Arial',
                  font_size=14,
                  font_color='grey',
                  title_font_color='black',
                  title_font_size=22,

                  xaxis_title='Ano',
                  yaxis_title='Número de imigrantes')

fig.show()

#Craindo dataFrame com todos os graficos de linhas dos Países da América do Sul, com a bliblioteca plotly

#america_sul = df.query('Região == "South America"')

america_sul.head()

df_america_sul_clean = america_sul.drop(['Continente', 'Região','Total'], axis=1)
america_sul_final = df_america_sul_clean.T

america_sul_final.head()

fig = px.line(america_sul_final, x=america_sul_final.index, y=america_sul_final.columns, color='País',
              title='Imigração da América do Sul para o Canadá no período de 1980 a 2013', markers=True)

fig.update_layout(
    xaxis={'tickangle':-45},
    xaxis_title='Ano',
    yaxis_title='Número de imigrantes',

)

fig.show()

#Salvando gráfico

fig.write_html('imigracao_america_sul.html')